import Head from 'next/head';
import Link from 'next/link';

import { useDispatch, useSelector } from 'react-redux';
import { selectAuthState, setAuthState } from '../store/authSlice';
import { wrapper } from '../store/store';

import styles from '@/styles/Home.module.css';

export default function Home() {
  const authState = useSelector(selectAuthState);
  const dispatch = useDispatch();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h5>home</h5>
          <Link href="/">Home</Link>
          <Link href="/signin">Signin</Link>
          <Link href="/signup">Signup</Link>
          <div>{authState ? "Logged in" : "Not Logged In"}</div>
          <button
            onClick={() =>
              authState
                ? dispatch(setAuthState(false))
                : dispatch(setAuthState(true))
            }
          >
            {authState ? "Logout" : "LogIn"}
          </button>
        </div>
      </main>
    </>
  )
}

// export const getServerSideProps = wrapper.getServerSideProps(
//   (store) =>
//     async ({ params }) => {
//       await store.dispatch(setAuthState(true));
//       console.log('State on server', store.getState());
//
//       return {
//         props: {
//           authState: true,
//         },
//       };
//     }
// );

