import Head from 'next/head';
import Link from 'next/link';

import { useSelector } from 'react-redux';
import { selectAuthState } from '@/store/authSlice';

import styles from '@/styles/Home.module.css';

export default function Signup() {
  const authState = useSelector(selectAuthState);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h5>signup</h5>
          <Link href="/">Home</Link>
          <Link href="/signin">Signin</Link>
          <Link href="/signup">Signup</Link>
          <div>{authState ? "Logged in" : "Not Logged In"}</div>
        </div>
      </main>
    </>
  )
}
